collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.583632
  brandStrength: 0.8118279
  lightness: 1
  brandColors:
    - '#020103'
    - '#FBE0C7'
    - '#D97827'
    - '#A44B03'
    - '#806D30'
  rhythmicContrast: 0.4964157
typography_spectrum: 0
layout_spectrum: 0.2132616
name: yTunes
