collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2419355
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.02568696
  brandColors:
    - '#1F0403'
    - '#FFFFFF'
    - '#FCCF01'
    - '#5B4B65'
    - '#029101'
  rhythmicContrast: 1
layout_spectrum: 0.005376308
name: yTunes
