collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5681913
color:
  saturation: 0.969534
  brandStrength: 0.8118279
  lightness: 0.983871
  brandColors:
    - '#1F0403'
    - '#FFFFFF'
    - '#FCCF01'
    - '#5B4B65'
    - '#029101'
  rhythmicContrast: 0.9707288
layout_spectrum: 0.005376308
name: yTunes
