collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0
color:
  saturation: 0.630227
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#0E0E0D'
    - '#FAFAF3'
    - '#423039'
    - '#78776E'
    - '#C6C5BE'
  lightness: 1
layout_spectrum: 0.98865
name: yTunes
